module CodeDiffsCUDA

using CodeDiffs
using CUDA
import CUDA: GPUCompiler

gpu_compiler_kwargs() = CUDA.COMPILER_KWARGS

include("gpu_common.jl")


function gpu_compiler_job(mi::Core.MethodInstance; kwargs...)
    config = CUDA.compiler_config(CUDA.device(); kwargs...)
    return CUDA.CompilerJob(mi, config)
end


function code_sass(job::CUDA.CompilerJob; kwargs...)
    @nospecialize(job)
    return sprint((io, job) -> CUDA.code_sass(io, job; kwargs...), job; context=:color=>false)
end


function code_sass(f, types; world=nothing, kwargs...)
    @nospecialize(f, types)
    compiler_kwargs, kwargs = split_kwargs(kwargs, gpu_compiler_kwargs())
    job = gpu_compiler_job(f, types, world; compiler_kwargs...)
    return code_sass(job; kwargs...)
end


CodeDiffs.argconvert(::Val{:cuda_typed},  arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:cuda_llvm},   arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:ptx},         arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:cuda_native}, arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:sass},        arg) = CUDA.cudaconvert(arg)

@nospecialize

CodeDiffs.get_code_dispatch(::Val{:cuda_typed},  f, types; kwargs...) = code_gpu_typed(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:cuda_llvm},   f, types; kwargs...) = code_gpu_llvm(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:ptx},         f, types; kwargs...) = CodeDiffs.get_code_dispatch(Val{:cuda_native}(), f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:cuda_native}, f, types; kwargs...) = code_gpu_native(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:sass},        f, types; kwargs...) = code_sass(f, types; kwargs...)

@specialize


CodeDiffs.code_highlighter(::Val{:cuda_typed})  = CodeDiffs.code_highlighter(Val{:typed}())
CodeDiffs.code_highlighter(::Val{:cuda_llvm})   = (io, str) -> highlight_using_pygments(io, str, "llvm")
CodeDiffs.code_highlighter(::Val{:ptx})         = (io, str) -> highlight_using_pygments(io, str, "ptx")
CodeDiffs.code_highlighter(::Val{:cuda_native}) = CodeDiffs.code_highlighter(Val{:ptx}())

function highlight_using_pygments(io::IO, str::AbstractString, lexer)
    if @static(Sys.iswindows() && lexer == "ptx")
        write(io, str)  # Pygments doesn't work for ptx on Windows
    else
        CUDA.GPUCompiler.highlight(io, str, lexer)
    end
end


# The PTX output of LLVM's NVPTX backend has a comment with the mangled function name
const PTX_FUNC_NAME_COMMENT_REGEX = r"// -- Begin function "m * CodeDiffs.MANGLED_NAME_REGEX * r"$"m

# Same with SASS but the name is surrounded by a lot of dashes
const SASS_FUNC_NAME_COMMENT_REGEX = r"//-{5,} .text."m * CodeDiffs.MANGLED_NAME_REGEX * r" -{5,}$"m


function CodeDiffs.cleanup_code(::Val{:cuda_llvm}, c)
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(CodeDiffs.LLVM_IR_FUNC_NAME_MANGLED_REGEX, c)
    return c
end

CodeDiffs.cleanup_code(::Val{:cuda_native}, c) = CodeDiffs.cleanup_code(Val{:ptx}(), c)
function CodeDiffs.cleanup_code(::Val{:ptx}, c)
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(PTX_FUNC_NAME_COMMENT_REGEX, c)
    c = cleanup_external_functions(c)
    c = CodeDiffs.demangle_all(c)  # Demangle only names which aren't the function's name
    return replace(c,
        # Remove the 3 extra header lines
        r"//\s//\sGenerated by LLVM NVPTX Back-End\s//\s\s" => "",
        # I don't know what `callseq` indicates in comments, but the numbers after change at every call
        r" // callseq .+$"m => "",
        # Remove 'inline asm' comments (remove the newline as well)
        r"^\s+// (begin|end) inline asm\R"m => "",
        # Remove empty lines
        r"\n{2,}" => "\n",
    )
end

function CodeDiffs.cleanup_code(::Val{:sass}, c)
    # SASS problems:
    # Registers seem to be assigned randomly, changing from one call to another with the
    # same input, as well as some immediate values (maybe related to the functions order in PTX?).
    # Some instructions (only `MOV` from what I saw) might be ordered differently, or even
    # in different numbers (max of what I could see is 1, but still surprising).
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(SASS_FUNC_NAME_COMMENT_REGEX, c)
    c = CodeDiffs.demangle_all(c)
    return c
end


function cleanup_external_functions(c)
    # In PTX code there can be external functions defined with the actual kernel function.
    # Those can have random positions, and their parameters can have names using the
    # `globalUniqueGeneratedNames` value.
    # To make the output consistent each time, we must filter the parameter names and order
    # the function definitions in a deterministic way.

    # Match external function definitions by following the PTX syntax:
    # https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=extern#linking-directives-extern
    # https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=extern#kernel-and-function-directives-func
    re_extern_func = r"\.extern \.func "s
    re_attribute_list = r"(?:\.attribute\(.+?\) )?"s
    re_func_name = r"(\w+)\s+"s  # Capture the function name
    re_param_list = r"\(.+?\)"s
    re_func_end = r"\s*;"s       # Since it is an external function it has no body
    re_extern_func_def = re_extern_func * re_attribute_list * re_func_name * re_param_list * re_func_end

    external_funcs = String[]
    for external_func in eachmatch(re_extern_func_def, c)
        func_def  = external_func.match
        func_name = external_func[1]

        param_idx = 0
        function rename_bad_param(_)
            new_name = func_name * "_param_" * string(param_idx)
            param_idx += 1
            return new_name
        end

        func_def = replace(func_def, func_name * r"_\d+_param" => rename_bad_param)
        push!(external_funcs, func_def)
    end

    isempty(external_funcs) && return c
    sort!(external_funcs)  # Basic attempt at ordering external functions, this might not be enough

    func_idx = 0
    function next_func_def(_)
        func_idx += 1
        return external_funcs[func_idx]
    end

    # Parse the code again but this time replace the external functions with the sorted ones
    return replace(c, re_extern_func_def => next_func_def)
end

end
