module CodeDiffsCUDA

using CodeDiffs
using CUDA
import CUDA: GPUCompiler
import KernelAbstractions as KA

gpu_compiler_kwargs() = CUDA.COMPILER_KWARGS

include("gpu_common.jl")


function CodeDiffs.extract_ka_backend_kwargs(kernel::KA.Kernel{CUDABackend})
    # Those two parameters are passed to the `@cuda` kernel constructor in `CUDA.CUDAKernels`
    backend = KA.backend(kernel)
    if KA.workgroupsize(kernel) <: KA.StaticSize
        workgroupsize = prod(KA.get(KA.workgroupsize(kernel)))
    else
        workgroupsize = nothing
    end
    return (; always_inline=backend.always_inline, maxthreads=workgroupsize)
end


function gpu_compiler_job(mi::Core.MethodInstance; kwargs...)
    config = CUDA.compiler_config(CUDA.device(); kwargs...)
    return CUDA.CompilerJob(mi, config)
end


function code_sass(job::CUDA.CompilerJob; dbinfo=true, kwargs...)
    @nospecialize(job)
    return sprint((io, job) -> CUDA.code_sass(io, job; kwargs...), job; context=:color=>false)
end


function code_sass(f, types; world=nothing, dbinfo=true, kwargs...)
    @nospecialize(f, types)
    compiler_kwargs, kwargs = split_kwargs(kwargs, gpu_compiler_kwargs())
    job = gpu_compiler_job(f, types, world; compiler_kwargs...)
    return code_sass(job; kwargs...)
end


CodeDiffs.argconvert(::Val{:cuda_typed},  arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:cuda_llvm},   arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:ptx},         arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:cuda_native}, arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:sass},        arg) = CUDA.cudaconvert(arg)
CodeDiffs.argconvert(::Val{:cuda_stats},  arg) = CUDA.cudaconvert(arg)

@nospecialize

CodeDiffs.get_code_dispatch(::Val{:cuda_typed},  f, types; kwargs...) = code_gpu_typed(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:cuda_llvm},   f, types; kwargs...) = code_gpu_llvm(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:ptx},         f, types; kwargs...) = CodeDiffs.get_code_dispatch(Val{:cuda_native}(), f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:cuda_native}, f, types; kwargs...) = code_gpu_native(f, types; kwargs...)
CodeDiffs.get_code_dispatch(::Val{:sass},        f, types; kwargs...) = code_sass(f, types; kwargs...)

function CodeDiffs.get_code_dispatch(::Val{:cuda_stats}, f, types; kwargs...)
    ptx_source = code_gpu_native(f, types; kwargs...)
    sass_source = code_sass(f, types; kwargs...)
    return extract_kernel_stats(ptx_source, sass_source)
end

@specialize


CodeDiffs.code_highlighter(::Val{:cuda_typed})  = CodeDiffs.code_highlighter(Val{:typed}())
CodeDiffs.code_highlighter(::Val{:cuda_llvm})   = (io, str) -> highlight_using_pygments(io, str, "llvm")
CodeDiffs.code_highlighter(::Val{:ptx})         = (io, str) -> highlight_using_pygments(io, str, "ptx")
CodeDiffs.code_highlighter(::Val{:cuda_native}) = CodeDiffs.code_highlighter(Val{:ptx}())

function highlight_using_pygments(io::IO, str::AbstractString, lexer)
    if @static(pkgversion(GPUCompiler) < v"1.2.0" && lexer == "ptx")
        write(io, str)
    else
        GPUCompiler.highlight(io, str, lexer)
    end
end


# The PTX output of LLVM's NVPTX backend has a comment with the mangled function name
const PTX_FUNC_NAME_COMMENT_REGEX = r"// -- Begin function "m * CodeDiffs.MANGLED_NAME_REGEX * r"$"m

# Same with SASS but the name is surrounded by a lot of dashes
const SASS_FUNC_NAME_COMMENT_REGEX = r"//-{5,} .text."m * CodeDiffs.MANGLED_NAME_REGEX * r" -{5,}$"m


function CodeDiffs.cleanup_code(::Val{:cuda_typed}, c, dbinfo, cleanup_opts)
    if get(cleanup_opts, :expand_llvmcall, true)
        c = CodeDiffs.cleanup_inline_llvmcall_modules(c)
    end
    return c
end


function CodeDiffs.cleanup_code(::Val{:cuda_llvm}, c, dbinfo, cleanup_opts)
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(CodeDiffs.LLVM_IR_FUNC_NAME_MANGLED_REGEX, c)
    return c
end


CodeDiffs.cleanup_code(::Val{:cuda_native}, c, dbinfo, cleanup_opts) =
    CodeDiffs.cleanup_code(Val{:ptx}(), c, dbinfo, cleanup_opts)

function CodeDiffs.cleanup_code(::Val{:ptx}, c, dbinfo, cleanup_opts)
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(PTX_FUNC_NAME_COMMENT_REGEX, c)
    c = cleanup_external_functions(c)
    if get(cleanup_opts, :demangle, true)
        c = CodeDiffs.demangle_all(c)  # Demangle only names which aren't the function's name
    end
    if get(cleanup_opts, :indent_calls, true)
        c = indent_ptx_function_calls(c)
    end
    return replace(c,
        # Remove the 3 extra header lines
        r"//\s//\sGenerated by LLVM NVPTX Back-End\s//\s\s" => "",
        # I don't know what `callseq` indicates in comments, but the numbers after change at every call
        r" // callseq .+$"m => "",
        # Remove 'inline asm' comments (remove the newline as well)
        r"^\s+// (begin|end) inline asm\R"m => "",
        # Remove the "end function" comment
        r"\s+// -- End function\n" => "",
        # Remove empty lines
        r"\n{2,}" => "\n",
    )
end


function CodeDiffs.cleanup_code(::Val{:sass}, c, dbinfo, cleanup_opts)
    # SASS problems:
    # Registers seem to be assigned randomly, changing from one call to another with the
    # same input, as well as some immediate values (maybe related to the functions order in PTX?).
    # Some instructions (only `MOV` from what I saw) might be ordered differently, or even
    # in different numbers (max of what I could see is 1, but still surprising).
    c = CodeDiffs.replace_llvm_module_name(c)
    c = CodeDiffs.clean_function_name(SASS_FUNC_NAME_COMMENT_REGEX, c)
    if get(cleanup_opts, :demangle, true)
        c = CodeDiffs.demangle_all(c)  # Demangle only names which aren't the function's name
    end
    if !dbinfo
        c = replace(c, r"; Location .+\n" => "")  # Remove location comments
    end
    return c
end


function cleanup_external_functions(c)
    # In PTX code there can be external functions defined with the actual kernel function.
    # Those can have random positions, and their parameters can have names using the
    # `globalUniqueGeneratedNames` value.
    # To make the output consistent each time, we must filter the parameter names and order
    # the function definitions in a deterministic way.

    # Match external function definitions by following the PTX syntax:
    # https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=extern#linking-directives-extern
    # https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=extern#kernel-and-function-directives-func
    re_extern_func = r"\.extern \.func "s
    re_attribute_list = r"(?:\.attribute\(.+?\) )?"s
    re_func_name = r"(\w+)\s+"s  # Capture the function name
    re_param_list = r"\(.+?\)"s
    re_func_end = r"\s*;"s       # Since it is an external function it has no body
    re_extern_func_def = re_extern_func * re_attribute_list * re_func_name * re_param_list * re_func_end

    external_funcs = String[]
    for external_func in eachmatch(re_extern_func_def, c)
        func_def  = external_func.match
        func_name = external_func[1]

        param_idx = 0
        function rename_bad_param(_)
            new_name = func_name * "_param_" * string(param_idx)
            param_idx += 1
            return new_name
        end

        func_def = replace(func_def, func_name * r"_\d+_param" => rename_bad_param)
        push!(external_funcs, func_def)
    end

    isempty(external_funcs) && return c
    sort!(external_funcs)  # Basic attempt at ordering external functions, this might not be enough

    func_idx = 0
    function next_func_def(_)
        func_idx += 1
        return external_funcs[func_idx]
    end

    # Parse the code again but this time replace the external functions with the sorted ones
    return replace(c, re_extern_func_def => next_func_def)
end


function indent_ptx_function_calls(c)
    # Matches `call func, (param_1, param_2...);`
    # Groups:
    #  - 1: call instruction options
    #  - 2: `func`
    #  - 3: parameters list
    ptx_call_regex = r"call(.*)\s+(.+),\s+\(([^;]+)\n\s+\);"

    function indent_call_params(call_inst)
        m = match(ptx_call_regex, call_inst)
        isnothing(m) && return call_inst
        indent = " "^8
        params = replace(m[3], "\n" => "\n" * indent)
        return "call" * m[1] * m[2] * ", (" * params * "\n" * indent * ");"
    end

    return replace(c, ptx_call_regex => indent_call_params)
end


function extract_kernel_ptx_stats(ptx_source)
    # Matches most PTX variable declarations, in any memory space (group "space"), with any
    # attributes (group "attributes"), and an optional array/parametric definition (group "array").
    # The data type is in group "type", and any vector attribute is in group "vec".
    # It accepts all valid PTX identifiers: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#identifiers
    # It does not support all declarations, namely multi-dimentional arrays, implicit array sizes
    # and mutliple declarations per line (".reg .b8 a, b, c;"). I have never seen those syntaxes
    # being generated by a compiler, so it shouldn't matter.
    mem_def_regex = r"\.(?'space'global|const|shared|local|reg)(?'attrs'(?:\s+\.(?:attribute\(.+\)|align \d+|(?'vec'v\d+)|(?'type'[busf]\d+|pred)|\w+))+)\s+[a-zA-Z0-9_$%]+(?'array'\[\d+\]|<\d+>)?"

    mem_definitions = Dict{String, Dict{String, Int}}()
    for mem_def in eachmatch(mem_def_regex, ptx_source)
        mem_space = String(mem_def[:space])
        data_type = isnothing(mem_def[:type]) ? "unknown" : String(mem_def[:type])

        if isnothing(mem_def[:array])
            count = 1
        else
            count = @something tryparse(Int, mem_def[:array][2:end-1]) 1
        end

        if !isnothing(mem_def[:vec])
            vec_size = @something tryparse(Int, mem_def[:vec][2:end]) 1
            count *= vec_size
        end

        mem_defs = get!(Dict{String, Int}, mem_definitions, mem_space)
        def_count = get(mem_defs, data_type, 0)
        mem_defs[data_type] = def_count + count
    end

    # Compute the total amount of memory for each memory space.
    # We only consider fundamental data types: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#fundamental-types
    # Predicate types (.pred) isn't listed since I don't know how it is stored in reality.
    fundamental_types = Dict(
        "b8" => 1, "b16" => 2, "b32" => 4, "b64" => 8, "b128" => 16,
        "s8" => 1, "s16" => 2, "s32" => 4, "s64" => 8,
        "u8" => 1, "u16" => 2, "u32" => 4, "u64" => 8,
                   "f16" => 2, "f32" => 4, "f64" => 8, "f16x2" => 4,
    )

    mem_sizes = Dict{String, Int}()
    for (mem_type, mem_defs) in pairs(mem_definitions)
        mem_size = 0
        for (data_type, count) in pairs(mem_defs)
            data_size = get(fundamental_types, data_type, 0)
            mem_size += data_size * count
        end
        mem_sizes[mem_type] = mem_size + get(mem_sizes, mem_type, 0)
    end

    return (;
        global_defs    = get(Dict{String, Int}, mem_definitions, "global"),
        constant_defs  = get(Dict{String, Int}, mem_definitions, "const"),
        shared_defs    = get(Dict{String, Int}, mem_definitions, "shared"),
        local_defs     = get(Dict{String, Int}, mem_definitions, "local"),
        registers_defs = get(Dict{String, Int}, mem_definitions, "reg"),
        total_global   = get(mem_sizes, "global", 0),
        total_constant = get(mem_sizes, "const", 0),
        total_shared   = get(mem_sizes, "shared", 0),
        total_local    = get(mem_sizes, "local",  0),
    )
end


function extract_kernel_sass_stats(sass_source)
    # The amount of registers per thread (I hope? This isn't documented anywhere...)
    m_reg = match(r"SHI_REGISTERS=(\d+)", sass_source)
    registers = isnothing(m_reg) ? 0 : @something(tryparse(Int, m_reg[1]), 0)

    # The SM version the kernel is compiled for
    m_sm = match(r"EF_CUDA_SM(\d+)", sass_source)
    SM = isnothing(m_sm) ? 0 : @something(tryparse(Int, m_sm[1]), 0)

    # This regex tries to match only SASS instructions, ignoring comments, attributes and labels,
    # but including predicates (starting with a "@"). We reject ':' in order to not match labels.
    sass_inst_regex = r"^\s*(@!?\w+\s+)?\w+[^;:]*;"m
    inst_count = count(sass_inst_regex, sass_source)

    # Stats about some notable instructions.
    # External function calls can have important overhead (in some cases, registers need to be
    # saved and restored around a call), so they are included.
    # See https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#instruction-set-reference
    # Obivously, it may change in future architectures.
    workgroup_sync = count("BSYNC", sass_source)
    warp_sync      = count("WARPSYNC", sass_source)
    function_calls = count("CALL", sass_source)

    return (; SM, registers, inst_count, workgroup_sync, warp_sync, function_calls)
end


struct CUDAKernelStats
    # PTX
    global_defs    :: Dict{String, Int}
    constant_defs  :: Dict{String, Int}
    shared_defs    :: Dict{String, Int}
    local_defs     :: Dict{String, Int}
    registers_defs :: Dict{String, Int}

    total_global   :: Int  # Total global memory used by the kernel variables (bytes)
    total_constant :: Int  # Total constant memory used by the kernel variables (bytes)
    total_shared   :: Int  # Total shared memory used by the kernel (bytes, for each workgroup)
    total_local    :: Int  # Total local memory used by the kernel (bytes, for each thread)

    # SASS
    SM             :: Int  # Target SM
    registers      :: Int  # Registers used per thread
    instructions   :: Int  # Number of instructions
    workgroup_sync :: Int  # Number of `BSYNC` instructions: `CUDA.sync_threads()`
    warp_sync      :: Int  # Number of `WARPSYNC` instructions: `CUDA.sync_warp()`
    calls          :: Int  # Number of `CALL`s to other functions
end


function extract_kernel_stats(ptx_source, sass_source)
    ptx_stats = extract_kernel_ptx_stats(ptx_source)
    sass_stats = extract_kernel_sass_stats(sass_source)
    return CUDAKernelStats(ptx_stats..., sass_stats...)
end


function Base.show(io::IO, stats::CUDAKernelStats)
    println(io, "Kernel memory stats (static allocations):")
    println(io, " - Global    ", Base.format_bytes(stats.total_global))
    println(io, " - Constant  ", Base.format_bytes(stats.total_constant))
    println(io, " - Shared    ", Base.format_bytes(stats.total_shared))
    println(io, " - Local     ", Base.format_bytes(stats.total_local))
    println(io)
    println(io, "SASS source stats:")
    println(io, " - Target SM         ", stats.SM)
    println(io, " - Registers usage   ", stats.registers)
    println(io, " - Instructions      ", stats.instructions)
    println(io, " - Workgroup sync    ", stats.workgroup_sync)
    println(io, " - Warp sync         ", stats.warp_sync)
    println(io, " - Function calls    ", stats.calls)
    println(io)

    # Since each `print` below might be the last one, we use 'print' instead of `println` to avoid a
    # trailing newline.
    print(io, "PTX variable declarations:")
    if all(isempty, (stats.global_defs, stats.constant_defs, stats.shared_defs, stats.local_defs, stats.registers_defs))
        print(io, " none")
        return
    end

    for (name, defs) in zip(
        ("Global", "Constant", "Shared", "Local", "Registers"),
        (stats.global_defs, stats.constant_defs, stats.shared_defs, stats.local_defs, stats.registers_defs),
    )
        isempty(defs) && continue
        print(io, "\n - ", name, ":")
        defs_list = collect(pairs(defs))
        sort!(defs_list; by=first)
        for (data_type, count) in defs_list
            print(io, "\n   - ", rpad(data_type, 5), " ", count)
        end
    end
end

end
