
# The GCN output of LLVM's AMDGPU backend has a comment with the mangled function name
const GCN_FUNC_NAME_COMMENT_REGEX = r"\.globl\s+"m * MANGLED_NAME_REGEX * r"\b"m


"""
    cleanup_code(::Val{:gcn}, code, dbinfo, cleanup_opts)

Cleanup GCN `code`.

Accepted `cleanup_opts` and their default values:
 - `metadata=false`: keep the metadata after the kernel's code
 - `kernel_metadata=false`: keep the YAML `amdhsa.kernels` section. It is removed if `metadata=false`.
 - `demangle=true`: demangle names within the code
 - `keep_loop_comments=false`: keep loop comments generated by the LLVM backend
 - `keep_block_comments=false`: keep code block comments generated by the LLVM backend
 - `keep_misc_comments=false`: keep other comments generated by the LLVM backend
 - `align_operands=24`: align the first operand of each instruction to the n-th column
"""
function cleanup_code(::Val{:gcn}, c, dbinfo, cleanup_opts)
    c = clean_function_name(GCN_FUNC_NAME_COMMENT_REGEX, c)

    extra_patterns = []

    if !get(cleanup_opts, :metadata, false)
        # Remove everything after the "; -- End function", as it is only metadata.
        func_end = findfirst(r"^\s*; -- End function"m, c)
        if !isnothing(func_end)
            c = c[1:first(func_end) - 1]
        end
    else
        # Remove the hundreds of '.ident "clang version ..."'  included in the metadata, as no
        # human being wants to see that. I am quite sure there is a bug somewhere which causes that...
        push!(extra_patterns, r"\t\.ident\t.+\n" => "")
    end
    if get(cleanup_opts, :demangle, true)
        push!(extra_patterns, demangle_all())
    end
    if !get(cleanup_opts, :keep_loop_comments, false)
        # Loop comments are interesting, but can be quite annoying with complex loop structures
        push!(extra_patterns, r"\R\s+;\s+(=>\s*)?(Parent|This|This Inner|Child|in) Loop[^\n]+" => "")
    end
    if !get(cleanup_opts, :keep_block_comments, false)
        # Block comments are placed after labels, or at the beginning of a line
        # They look like "some_label: ; %blabla" or "; %blabla".
        push!(extra_patterns, r"(^\.\w+:)?(?:\s*); %.+"m => s"\1")
    end
    if !get(cleanup_opts, :keep_misc_comments, false)
        # Remove "; divergent unreachable" comments and others
        push!(extra_patterns,
            r"\R\s*; divergent unreachable"m => "",
            r"\R\s*; implicit-def:.+$"m => "",
        )
    end
    if !get(cleanup_opts, :kernel_metadata, false)
        # Kernel metadata is stored within its dedicated ".amdhsa_kernel" section.
        # It is a bit large and somewhat relevant to the code, therefore we remove it by default.
        push!(extra_patterns, r"^\s*\.amdhsa_kernel.+\.end_amdhsa_kernel\R"sm => "")
    end
    if (align_operands = get(cleanup_opts, :align_operands, 24); align_operands > 0)
        # Align instruction operands such that the first operand is at the `align_operands` column.
        push!(extra_patterns, align_instruction_operand(align_operands))
    end

    c = replace(c,
        llvm_module_name_patterns()...,
        # This "begin" comment is redundant
        r"\s*; -- Begin function.+$"m => "",
        extra_patterns...,
    )

    # GCN doesn't have any instruction guards, so 4 spaces is enough.
    c = replace(c, replace_tabs(4))
    return rstrip(c)  # remove trailing newlines
end


function align_instruction_operand(column)
    # The regex extracts the operands from "   any_instruction ops..." to the second match group.
    # In order to remove any trailing spaces, we also match the case when there are no operands.
    operand_regex = r"^\s*\w+(\h+)(.*)$"m

    function align_to_nth_column(c)
        m = match(operand_regex, c)
        isnothing(m) && return c

        mnemonic_end = m.offsets[1]

        if all(isspace, m[2])
            # In case the operands are just trailing spaces, return only the mnemonic
            return m.match[1:mnemonic_end-1]
        end

        # Place the operand at the `column`, unless the mnemonic is too long
        if mnemonic_end ≥ column
            return c
        else
            extra_spaces = " "^(column - mnemonic_end)
            return m.match[1:mnemonic_end-1] * extra_spaces * m[2]
        end
    end

    return operand_regex => align_to_nth_column
end
