
struct PTXStats
    defs :: @NamedTuple{
        var"global" :: Dict{String, Int},
        constant    :: Dict{String, Int},
        param       :: Dict{String, Int},
        shared      :: Dict{String, Int},
        var"local"  :: Dict{String, Int},
        registers   :: Dict{String, Int},
    }

    uses_dynamic_shared_mem :: Bool

    total :: @NamedTuple{
        var"global" :: Int,  # Total global memory used by the kernel variables (bytes)
        constant    :: Int,  # Total constant memory used by the kernel variables (bytes)
        param       :: Int,  # Total constant memory used by the kernel variables (bytes)
        shared      :: Int,  # Total shared memory used by the kernel (bytes, for each workgroup)
        var"local"  :: Int,  # Total local memory used by the kernel (bytes, for each thread)
    }

    inst :: @NamedTuple{
        var"global" :: @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}},
        constant    :: @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}},
        param       :: @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}},
        shared      :: @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}},
        var"local"  :: @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}},
    }
end


function Base.:(==)(a::PTXStats, b::PTXStats)
    return a.defs == b.defs &&
           a.uses_dynamic_shared_mem == b.uses_dynamic_shared_mem &&
           a.total == b.total &&
           a.inst == b.inst
end


function extract_stats(::Val{:ptx}, ptx_source, stats_opts)
    # Matches most PTX variable declarations, in any memory space (group "space"), with any
    # attributes (group "attributes"), and an optional array/parametric definition (group "array").
    # The data type is in group "type", and any vector attribute is in group "vec".
    # It accepts all valid PTX identifiers: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#identifiers
    # It does not support all declarations, namely multi-dimentional arrays and mutliple declarations
    # per line (".reg .b8 a, b, c;"). I have never seen those syntaxes being generated by a compiler,
    # so it shouldn't matter.
    mem_def_regex = r"\.(?'space'global|const|param|shared|local|reg)(?'attrs'(?:\s+\.(?:attribute\(.+\)|align \d+|(?'vec'v\d+)|(?'type'[busf]\d+|pred)|\w+))+)\s+[a-zA-Z0-9_$%]+(?'array'\[\d+\]|<\d+>)?"

    # The `mem_def_regex` considers all `.param` declarations, even those which are in `.extern`
    # functions, which is wrong. To avoid changing the `mem_def_regex` we must ignore matches within
    # extern function definitions.
    extern_func_regex = r"\.extern\s+\.func[^;]+"

    extern_func_regions = Vector{UnitRange{Int}}()
    last_extern_def = 0
    for extern_func_def in eachmatch(extern_func_regex, ptx_source)
        region = (1:length(extern_func_def.match)) .+ (extern_func_def.offset - 1)
        push!(extern_func_regions, region)
        last_extern_def = max(last_extern_def, last(region))
    end

    mem_definitions = Dict{String, Dict{String, Int}}()
    for mem_def in eachmatch(mem_def_regex, ptx_source)
        if mem_def.offset ≤ last_extern_def && any(Ref(mem_def.offset) .∈ extern_func_regions)
            # The variable definition is in an extern function, so it must be ignored.
            continue
        end

        mem_space = String(mem_def[:space])
        data_type = String(@something mem_def[:type] "unknown")

        if isnothing(mem_def[:array])
            count = 1
        elseif mem_def[:array] == "[]" && mem_space == "shared"
            # Dynamic shared memory is declared using an array with an implicit size
            mem_space = "dyn_shared"
            count = 0
        else
            count = @something tryparse(Int, mem_def[:array][2:end-1]) 1
        end

        if !isnothing(mem_def[:vec])
            vec_size = @something tryparse(Int, mem_def[:vec][2:end]) 1
            count *= vec_size
        end

        mem_defs = get!(Dict{String, Int}, mem_definitions, mem_space)
        def_count = get(mem_defs, data_type, 0)
        mem_defs[data_type] = def_count + count
    end

    # Matches all variations (hopefully) of the `ld`, `ld.global.nc`, `ldu`, `st`, `st.async` and `st.bulk`
    # instructions: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#data-movement-and-conversion-instructions-ld
    # The leading instruction mnemonic is in group "inst". The memory space is in group "space", and
    # does not include the optional "::cta" or "::cluster" which can be found for some variants.
    # The vector size (if any) is in group "vec". The data type is in group "type". Additional
    # attributes are discarded.
    mem_inst_regex = r"\b(?'inst'ld|ldu|st)(?:\.(?:(?'space'global|const|param|shared|local)(?:::[^\s\.]+)?|(?'vec'v\d+)|(?'type'[busf]\d+)|[^\s\.]+))+\b"

    mem_instructions = Dict{String, @NamedTuple{loads::Dict{String, Int}, stores::Dict{String, Int}}}()
    for mem_inst in eachmatch(mem_inst_regex, ptx_source)
        is_load   = mem_inst[:inst] in ("ld", "ldu")
        mem_space = String(@something mem_inst[:space] "global")  # Assume that all generic addressing goes to global memory
        data_type = String(@something mem_inst[:type] "unknown")

        count = 1
        if !isnothing(mem_inst[:vec])
            vec_size = @something tryparse(Int, mem_inst[:vec][2:end]) 1
            count *= vec_size
        end

        mem_insts = get!(mem_instructions, mem_space) do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end
        inst_counts = is_load ? mem_insts.loads : mem_insts.stores
        inst_count = get(inst_counts, data_type, 0)
        inst_counts[data_type] = inst_count + count
    end

    # Compute the total amount of memory within all variable declarations for each memory space.
    # We only consider fundamental data types: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#fundamental-types
    # Predicate types (.pred) are not listed since I don't know how it is stored in reality.
    fundamental_types = Dict(
        "b8" => 1, "b16" => 2, "b32" => 4, "b64" => 8, "b128" => 16,
        "s8" => 1, "s16" => 2, "s32" => 4, "s64" => 8,
        "u8" => 1, "u16" => 2, "u32" => 4, "u64" => 8,
                   "f16" => 2, "f32" => 4, "f64" => 8, "f16x2" => 4,
    )

    mem_sizes = Dict{String, Int}()
    for (mem_type, mem_defs) in pairs(mem_definitions)
        mem_size = 0
        for (data_type, count) in pairs(mem_defs)
            data_size = get(fundamental_types, data_type, 0)
            mem_size += data_size * count
        end
        mem_sizes[mem_type] = mem_size + get(mem_sizes, mem_type, 0)
    end

    return PTXStats(
        (;
            var"global" = get(Dict{String, Int}, mem_definitions, "global"),
            constant    = get(Dict{String, Int}, mem_definitions, "const"),
            param       = get(Dict{String, Int}, mem_definitions, "param"),
            shared      = get(Dict{String, Int}, mem_definitions, "shared"),
            var"local"  = get(Dict{String, Int}, mem_definitions, "local"),
            registers   = get(Dict{String, Int}, mem_definitions, "reg"),
        ),
        # Since dynamic shared memory uses a single declaration for all arrays, there is no point in
        # having details about it.
        haskey(mem_definitions, "dyn_shared"),
        (;
            var"global" = get(mem_sizes, "global", 0),
            constant    = get(mem_sizes, "const",  0),
            param       = get(mem_sizes, "param",  0),
            shared      = get(mem_sizes, "shared", 0),
            var"local"  = get(mem_sizes, "local",  0),
        ),
        (;
            var"global" = get(mem_instructions, "global") do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end,
            constant    = get(mem_instructions, "const")  do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end,
            param       = get(mem_instructions, "param")  do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end,
            shared      = get(mem_instructions, "shared") do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end,
            var"local"  = get(mem_instructions, "local")  do ; (; loads=Dict{String, Int}(), stores=Dict{String, Int}()) end,
        ),
    )
end


struct SASSStats
    SM             :: Int  # Target SM
    registers      :: Int  # Registers used per thread
    instructions   :: Int  # Number of instructions
    workgroup_sync :: Int  # Number of `BSYNC` instructions: `CUDA.sync_threads()`
    warp_sync      :: Int  # Number of `WARPSYNC` instructions: `CUDA.sync_warp()`
    calls          :: Int  # Number of `CALL`s to other functions
end


function Base.:(==)(a::SASSStats, b::SASSStats)
    return a.SM == b.SM &&
           a.registers == b.registers &&
           a.workgroup_sync == b.workgroup_sync &&
           a.warp_sync == b.warp_sync &&
           a.calls == b.calls
end


function extract_stats(::Val{:sass}, sass_source, stats_opts)
    # The amount of registers per thread (I hope? This isn't documented anywhere...)
    m_reg = match(r"SHI_REGISTERS=(\d+)", sass_source)
    registers = isnothing(m_reg) ? 0 : @something(tryparse(Int, m_reg[1]), 0)

    # The SM version the kernel is compiled for
    m_sm = match(r"EF_CUDA_SM(\d+)", sass_source)
    SM = isnothing(m_sm) ? 0 : @something(tryparse(Int, m_sm[1]), 0)

    # This regex tries to match only SASS instructions, ignoring comments, attributes and labels,
    # but including predicates (starting with a "@"). We reject ':' in order to not match labels.
    sass_inst_regex = r"^\s*(@!?\w+\s+)?\w+[^;:]*;"m
    inst_count = count(sass_inst_regex, sass_source)

    # Stats about some notable instructions.
    # External function calls can have important overhead (in some cases, registers need to be
    # saved and restored around a call), so they are included.
    # See https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#instruction-set-reference
    # Obivously, it may change in future architectures.
    workgroup_sync = count("BSYNC", sass_source)
    warp_sync      = count("WARPSYNC", sass_source)
    function_calls = count("CALL", sass_source)

    return SASSStats(SM, registers, inst_count, workgroup_sync, warp_sync, function_calls)
end


struct CUDAKernelStats
    ptx  :: PTXStats
    sass :: SASSStats
end


Base.:(==)(a::CUDAKernelStats, b::CUDAKernelStats) = a.ptx == b.ptx && a.sass == b.sass


function extract_stats(::Val{:cuda_stats}, (ptx_source, sass_source), stats_opts)
    ptx_stats = extract_stats(Val(:ptx), ptx_source, stats_opts)
    sass_stats = extract_stats(Val(:sass), sass_source, stats_opts)
    return CUDAKernelStats(ptx_stats, sass_stats)
end


function cmp_ptx_type(a::AbstractString, b::AbstractString)
    # `isless` for pretty sorting a list of PTX types.
    # We only consider fundamental PTX types, which simplifies things a lot.
    # See https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=global#fundamental-types
    (isempty(a) || isempty(b)) && return a < b

    # Hardcoded ordering, for simplicity
    type_order = ('p' #= pred =#, 'b', 'u', 's', 'f')
    size_order = ("8", "16", "16x2", "32", "64", "128")

    # Assume first char is type, and the rest is the size, to transparently handle the "pred" type
    a_type_idx = @something findfirst(==(@inbounds a[1]), type_order) 1000
    b_type_idx = @something findfirst(==(@inbounds b[1]), type_order) 1000
    a_size_idx = @something findfirst(==(@view a[2:end]), size_order) 1000
    b_size_idx = @something findfirst(==(@view b[2:end]), size_order) 1000

    return (a_type_idx, a_size_idx) < (b_type_idx, b_size_idx)
end


function Base.show(io::IO, ::MIME"text/plain", stats::PTXStats)
    println(io, "Kernel memory stats (static allocations):")
    println(io, " - Global  ", Base.format_bytes(stats.total.global))
    println(io, " - Const   ", Base.format_bytes(stats.total.constant))
    println(io, " - Param   ", Base.format_bytes(stats.total.param))
    println(io, " - Shared  ", Base.format_bytes(stats.total.shared))
    println(io, " - Local   ", Base.format_bytes(stats.total.local))
    if stats.uses_dynamic_shared_mem
        println(io, " - Uses dynamic shared memory")
    end

    print(io, "\nPTX variable declarations:")
    all(isempty, stats.defs) && print(io, " none")
    for (name, defs) in pairs(stats.defs)
        isempty(defs) && continue
        print(io, "\n - ", uppercasefirst(String(name)), ":")
        defs_list = collect(pairs(defs))
        sort!(defs_list; by=first, lt=cmp_ptx_type)
        for (data_type, count) in defs_list
            print(io, "\n   - ", rpad(data_type, 5), " ", lpad(count, 5))
        end
    end

    print(io, "\n\nPTX memory instructions (loads, stores):")
    all(isempty, stats.inst) && print(io, " none")
    for (name, space) in pairs(stats.inst)
        all(isempty, space) && continue
        print(io, "\n - ", uppercasefirst(String(name)), ":")
        types = collect(keys(space.loads) ∪ keys(space.stores))
        sort!(types; lt=cmp_ptx_type)
        for data_type in types
            ld_count = get(space.loads,  data_type, 0)
            st_count = get(space.stores, data_type, 0)
            print(io, "\n   - ", rpad(data_type, 5), " ", lpad(ld_count, 5), " ", lpad(st_count, 5))
        end
    end
end


function Base.show(io::IO, ::MIME"text/plain", stats::SASSStats)
    println(io, "SASS source stats:")
    println(io, " - SM version        ", stats.SM)
    println(io, " - Registers usage   ", stats.registers)
    println(io, " - Instructions      ", stats.instructions)
    println(io, " - Workgroup sync    ", stats.workgroup_sync)
    println(io, " - Warp sync         ", stats.warp_sync)
    print(io,   " - Function calls    ", stats.calls)
end


function Base.show(io::IO, ::MIME"text/plain", stats::CUDAKernelStats)
    show(io, MIME"text/plain"(), stats.ptx)
    println(io)
    println(io)
    show(io, MIME"text/plain"(), stats.sass)
end

